# ==========================================
# CORE LIBRARY: CHEMICAL FUNCTIONS & XTB WRAPPERS
# ==========================================

import os
import re
import shutil
import subprocess
import math
import textwrap
from typing import Tuple, List, Optional
from dataclasses import dataclass
import numpy as np
from collections import Counter

from rdkit import Chem
from rdkit.Chem import AllChem, rdMolAlign
from rdkit.Geometry import Point3D

HARTREE_TO_KCAL = 627.509474

# --- Utility Functions ---
def _write_text(path: str, text: str) -> None:
    with open(path, "w", encoding="utf-8") as f: f.write(text)

def _read_text(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f: return f.read()

def _split_reaction_smiles(rxn_smiles: str) -> Tuple[str, str]:
    try: lhs, rhs = rxn_smiles.split(">>")
    except ValueError: raise ValueError("Reaction SMILES sai format")
    return lhs.strip(), rhs.strip()

def _combine_mols_from_smiles(smiles: str) -> Chem.Mol:
    m = Chem.MolFromSmiles(smiles, sanitize=False)
    if m is None: raise ValueError(f"Bad SMILES: {smiles}")
    atom_map_order = sorted([(a.GetIdx(), a.GetAtomMapNum()) for a in m.GetAtoms()], key=lambda x: x[1])
    new_order = [x[0] for x in atom_map_order]
    m = Chem.RenumberAtoms(m, new_order)
    try: Chem.SanitizeMol(m)
    except:
        try: Chem.SanitizeMol(m, Chem.SanitizeFlags.SANITIZE_ALL ^ Chem.SanitizeFlags.SANITIZE_KEKULIZE)
        except: pass
    return m

def _mol_to_xyz(mol: Chem.Mol) -> str:
    if mol.GetNumConformers() == 0: raise ValueError("RDKit 0 conformers generated.")
    conf = mol.GetConformer()
    lines = []
    for i, a in enumerate(mol.GetAtoms()):
        p = conf.GetAtomPosition(i)
        lines.append(f"{a.GetSymbol():2s} {p.x: .10f} {p.y: .10f} {p.z: .10f}")
    return f"{mol.GetNumAtoms()}\nGenerated by RDKit\n" + "\n".join(lines) + "\n"

def get_bond_list(mol: Chem.Mol) -> List[Tuple[int, int]]:
    bonds = []
    for b in mol.GetBonds():
        idx1 = b.GetBeginAtomIdx() + 1; idx2 = b.GetEndAtomIdx() + 1
        bonds.append((idx1, idx2))
    return bonds

def is_non_polar_small_fragment(mol: Chem.Mol) -> bool:
    if mol.GetNumAtoms() != 2: return False
    atoms = [a.GetSymbol() for a in mol.GetAtoms()]
    if all(x == 'H' for x in atoms): return True
    if all(x == 'N' for x in atoms): return True
    if all(x == 'O' for x in atoms): return True
    return False

# --- Strategy Tools ---
def perform_geometric_docking(mol: Chem.Mol, bond_pair: Tuple[int, int], target_dist: float = 3.0) -> Chem.Mol:
    if not bond_pair: return mol
    idx1, idx2 = bond_pair
    frags = list(Chem.GetMolFrags(mol, asMols=False))
    if len(frags) < 2: return mol 

    frag1_idx = -1; frag2_idx = -1
    for i, f in enumerate(frags):
        if idx1 in f: frag1_idx = i
        if idx2 in f: frag2_idx = i
    
    if frag1_idx == frag2_idx: return mol

    f1_atoms = frags[frag1_idx]
    f2_atoms = frags[frag2_idx]
    
    anchor_idx, mobile_idx = idx1, idx2
    anchor_frag, mobile_frag = f1_atoms, f2_atoms
    
    if len(f1_atoms) < len(f2_atoms):
        anchor_idx, mobile_idx = idx2, idx1
        anchor_frag, mobile_frag = f2_atoms, f1_atoms

    conf = mol.GetConformer()
    p_anchor = np.array(conf.GetAtomPosition(anchor_idx))
    center_anchor = np.mean([np.array(conf.GetAtomPosition(i)) for i in anchor_frag], axis=0)
    
    vec_out = p_anchor - center_anchor
    norm = np.linalg.norm(vec_out)
    if norm < 0.1: vec_out = np.array([1.0, 0, 0])
    else: vec_out /= norm

    target_pos_mobile = p_anchor + vec_out * target_dist
    p_mobile_current = np.array(conf.GetAtomPosition(mobile_idx))
    translation = target_pos_mobile - p_mobile_current
    
    for i in mobile_frag:
        p = np.array(conf.GetAtomPosition(i))
        p_new = p + translation
        conf.SetAtomPosition(i, Point3D(*p_new))
        
    return mol

def generate_best_conformer(mol: Chem.Mol, num_confs: int = 200, seed: int = 42) -> Chem.Mol:
    mol = Chem.AddHs(mol, addCoords=True)
    ps = AllChem.ETKDGv3(); ps.randomSeed = seed; ps.useRandomCoords = True;
    ids = AllChem.EmbedMultipleConfs(mol, numConfs=num_confs, params=ps)
    if not ids:
        ps.useRandomCoords = True; ps.maxAttempts = 2000
        try: ids = AllChem.EmbedMultipleConfs(mol, numConfs=num_confs, params=ps)
        except: AllChem.EmbedMolecule(mol, useRandomCoords=True); ids=[0]

    min_e = float('inf'); best_id = -1
    for cid in range(mol.GetNumConformers()):
        try:
            ff = AllChem.MMFFGetMoleculeForceField(mol, confId=cid)
            if ff.Minimize() == 0:
                e = ff.CalcEnergy()
                if e < min_e: min_e = e; best_id = cid
        except: pass
    final_mol = Chem.Mol(mol); final_mol.RemoveAllConformers()
    if best_id != -1: final_mol.AddConformer(mol.GetConformer(best_id))
    elif mol.GetNumConformers() > 0: final_mol.AddConformer(mol.GetConformer(0))
    return final_mol

def align_molecules_by_map(probe_mol: Chem.Mol, ref_mol: Chem.Mol) -> Chem.Mol:
    if probe_mol.GetNumConformers() == 0 or ref_mol.GetNumConformers() == 0: return probe_mol
    ref_map = {a.GetAtomMapNum(): a.GetIdx() for a in ref_mol.GetAtoms() if a.GetAtomMapNum() > 0}
    probe_map = {a.GetAtomMapNum(): a.GetIdx() for a in probe_mol.GetAtoms() if a.GetAtomMapNum() > 0}
    atom_pairs = []
    for map_num, ref_idx in ref_map.items():
        if map_num in probe_map: atom_pairs.append((probe_map[map_num], ref_idx))
    if atom_pairs:
        try: rdMolAlign.AlignMol(probe_mol, ref_mol, atomMap=atom_pairs, reflect=True)
        except: pass
    return probe_mol

def generate_from_template(template_mol: Chem.Mol, target_bonds: List[Tuple[int, int]], stretch_dist: float = 3.2) -> Chem.Mol:
    generated_mol = Chem.Mol(template_mol)
    conf = generated_mol.GetConformer()
    map_to_idx = {a.GetAtomMapNum(): a.GetIdx() for a in generated_mol.GetAtoms() if a.GetAtomMapNum() > 0}
    bond_pair = None
    for m1, m2 in target_bonds:
        if m1 in map_to_idx and m2 in map_to_idx:
            bond_pair = (map_to_idx[m1], map_to_idx[m2]); break
    if bond_pair:
        idx1, idx2 = bond_pair
        p1 = np.array(conf.GetAtomPosition(idx1)); p2 = np.array(conf.GetAtomPosition(idx2))
        vec = p2 - p1; norm = np.linalg.norm(vec)
        if norm < 0.1: vec = np.array([1.0, 0, 0])
        else: vec /= norm
        move_vec = vec * (stretch_dist - norm)
        rw = Chem.RWMol(generated_mol); rw.RemoveBond(idx1, idx2)
        frags = Chem.GetMolFrags(rw, asMols=False)
        if len(frags) >= 2:
            frag_move_idx = -1
            for i, f in enumerate(frags):
                if idx2 in f: frag_move_idx = i; break
            for at_idx in frags[frag_move_idx]:
                p_old = np.array(conf.GetAtomPosition(at_idx))
                p_new = p_old + move_vec
                conf.SetAtomPosition(at_idx, Point3D(float(p_new[0]), float(p_new[1]), float(p_new[2])))
    return generated_mol

def get_rc_bonds_indices(mol, forming_map, breaking_map):
    map_to_idx = {a.GetAtomMapNum(): a.GetIdx() for a in mol.GetAtoms() if a.GetAtomMapNum() > 0}
    rc_bonds = []
    for m1, m2 in forming_map + breaking_map:
        if m1 in map_to_idx and m2 in map_to_idx:
            i1, i2 = map_to_idx[m1], map_to_idx[m2]
            rc_bonds.append((i1 + 1, i2 + 1))
    return rc_bonds

# --- xTB Optimizers ---
def xtb_optimize_double_step(xyz_text: str, workdir: str, prefix: str, rc_bonds: List[Tuple[int, int]],
                             gfn: int = 2, alpb: Optional[str] = None, nproc: int = 2,
                             charge: int = 0, uhf: int = 0) -> Tuple[str, Optional[float]]:
    os.makedirs(workdir, exist_ok=True)
    init_path = os.path.join(workdir, f"{prefix}_init.xyz")
    _write_text(init_path, xyz_text)

    # STEP 1
    constrain_s1 = ["$constrain", "  force constant=0.3"]
    for b1, b2 in rc_bonds: constrain_s1.append(f"  bond: {b1}, {b2}")
    constrain_s1.append("$end")
    _write_text(os.path.join(workdir, "step1.inp"), "\n".join(constrain_s1))

    cmd1 = ["xtb", os.path.basename(init_path), "--opt", "tight", "--input", "step1.inp",
            "--gfn", str(gfn), "--chrg", str(charge), "--uhf", str(uhf)]
    if alpb: cmd1 += ["--alpb", alpb]
    _run_xtb(cmd1, cwd=workdir, nproc=nproc)

    # STEP 2
    constrain_s2 = ["$constrain", "  force constant=0.02"]
    for b1, b2 in rc_bonds: constrain_s2.append(f"  bond: {b1}, {b2}")
    constrain_s2.append("$end")
    _write_text(os.path.join(workdir, "step2.inp"), "\n".join(constrain_s2))

    cmd2 = ["xtb", "xtbopt.xyz", "--opt", "normal", "--input", "step2.inp",
            "--gfn", str(gfn), "--chrg", str(charge), "--uhf", str(uhf)]
    if alpb: cmd2 += ["--alpb", alpb]
    out2 = _run_xtb(cmd2, cwd=workdir, nproc=nproc)

    energy_kcal = None
    m = re.search(r"TOTAL ENERGY\s*[:=]\s*([-\d.]+)", out2, re.IGNORECASE)
    if m: energy_kcal = float(m.group(1)) * HARTREE_TO_KCAL
    final_xyz = os.path.join(workdir, f"{prefix}_opt.xyz")
    if os.path.exists(os.path.join(workdir, "xtbopt.xyz")): shutil.move(os.path.join(workdir, "xtbopt.xyz"), final_xyz)
    else: final_xyz = init_path
    return final_xyz, energy_kcal

# --- Builder ---
def build_start_end_xyz_smart(rxn_smiles: str, seed: int = 42, num_confs: int = 200,
                              force_independent: bool = False, target_dist: float = 3.0):
    lhs_smi, rhs_smi = _split_reaction_smiles(rxn_smiles)
    num_reactants = lhs_smi.count('.') + 1
    num_products = rhs_smi.count('.') + 1

    lhs_mol_base = _combine_mols_from_smiles(lhs_smi)
    rhs_mol_base = _combine_mols_from_smiles(rhs_smi)

    def get_map_bonds(mol):
        bonds = set()
        for b in mol.GetBonds():
            a1, a2 = b.GetBeginAtom().GetAtomMapNum(), b.GetEndAtom().GetAtomMapNum()
            if a1>0 and a2>0: bonds.add(tuple(sorted((a1, a2))))
        return bonds
    lhs_bonds_map = get_map_bonds(lhs_mol_base)
    rhs_bonds_map = get_map_bonds(rhs_mol_base)
    forming_map = list(rhs_bonds_map - lhs_bonds_map)
    breaking_map = list(lhs_bonds_map - rhs_bonds_map)

    use_template_strategy = False
    template_side = None
    opt_mode = "double"
    current_target_dist = 2.0
    strategy_type = "INDEPENDENT"

    has_gas_react = any(is_non_polar_small_fragment(m) for m in Chem.GetMolFrags(lhs_mol_base, asMols=True))
    has_gas_prod  = any(is_non_polar_small_fragment(m) for m in Chem.GetMolFrags(rhs_mol_base, asMols=True))
    is_many_to_many = (num_reactants >= 2 and num_products >= 2)

    if force_independent:
        use_template_strategy = False
        current_target_dist = target_dist
        strategy_type = "INDEPENDENT"
    elif (has_gas_react or has_gas_prod) and (num_reactants != num_products) and not is_many_to_many:
        use_template_strategy = True
        if has_gas_react:
            template_side = 'product'
            strategy_type = "PRODUCT_TEMPLATE"
        else:
            template_side = 'reactant'
            strategy_type = "REACTANT_TEMPLATE"
    else:
        use_template_strategy = False
        current_target_dist = 2.0
        strategy_type = "INDEPENDENT"

    if use_template_strategy:
        if template_side == 'product':
            product_template = generate_best_conformer(rhs_mol_base, num_confs, seed)
            reactant_gen = generate_from_template(product_template, forming_map, stretch_dist=3.0)
            return (_mol_to_xyz(reactant_gen), _mol_to_xyz(product_template),
                    reactant_gen, product_template, breaking_map, forming_map, opt_mode, strategy_type)
        else:
            reactant_template = generate_best_conformer(lhs_mol_base, num_confs, seed)
            product_gen = generate_from_template(reactant_template, breaking_map, stretch_dist=3.0)
            return (_mol_to_xyz(reactant_template), _mol_to_xyz(product_gen),
                    reactant_template, product_gen, breaking_map, forming_map, opt_mode, strategy_type)
    else:
        reactant_best = generate_best_conformer(lhs_mol_base, num_confs, seed)
        product_best = generate_best_conformer(rhs_mol_base, num_confs, seed+1)

        def map_to_idx_tuple(mol, map_tuple):
            d = {a.GetAtomMapNum(): a.GetIdx() for a in mol.GetAtoms()}
            if map_tuple[0] in d and map_tuple[1] in d: return (d[map_tuple[0]], d[map_tuple[1]])
            return None

        if forming_map and num_reactants > 1:
            for bond_map in forming_map:
                pair = map_to_idx_tuple(reactant_best, bond_map)
                if pair: perform_geometric_docking(reactant_best, pair, target_dist=current_target_dist)

        if breaking_map and num_products > 1:
            for bond_map in breaking_map:
                pair = map_to_idx_tuple(product_best, bond_map)
                if pair: perform_geometric_docking(product_best, pair, target_dist=current_target_dist)

        product_best = align_molecules_by_map(product_best, reactant_best)
        return (_mol_to_xyz(reactant_best), _mol_to_xyz(product_best),
                reactant_best, product_best, breaking_map, forming_map, opt_mode, strategy_type)

# --- xTB Runner Utils ---
@dataclass
class PathTrial:
    index: int; barrier_kcal: float; dE_kcal: float; prod_rmsd: Optional[float]

def check_atom_consistency(txt1: str, txt2: str) -> bool:
    def get_cnt(t):
        lines = t.strip().splitlines()
        if len(lines) < 3: return Counter()
        return Counter([l.split()[0] for l in lines[2:] if l.strip()])
    c1 = get_cnt(txt1); c2 = get_cnt(txt2)
    return c1 == c2

def _run_xtb(cmd: List[str], cwd: str, nproc: int) -> str:
    env = os.environ.copy(); env["OMP_NUM_THREADS"] = str(int(nproc)); env["OMP_STACKSIZE"] = "4G"
    proc = subprocess.run(cmd, cwd=cwd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, check=False)
    return proc.stdout or ""

def _parse_xtb_run_table(output: str) -> List[PathTrial]:
    runs: List[PathTrial] = []
    pat_full = re.compile(r"run\s*?(\d+)\s+barrier:\s*([-\d.]+)\s+dE:\s*([-\d.]+)\s+product-end\s+path\s+RMSD:\s*([-\d.]+)", re.IGNORECASE)
    for m in pat_full.finditer(output): runs.append(PathTrial(int(m.group(1)), float(m.group(2)), float(m.group(3)), float(m.group(4))))
    if not runs:
        pat = re.compile(r"run\s*?(\d+)\s+barrier:\s*([-\d.]+)\s+dE:\s*([-\d.]+)", re.IGNORECASE)
        for m in pat.finditer(output): runs.append(PathTrial(int(m.group(1)), float(m.group(2)), float(m.group(3)), None))
    return runs

def run_xtb_path_once(start_xyz_text: str, end_xyz_text: str, workdir: str, gfn: int, nproc: int, alpb: Optional[str], npoint: int, kpush: float, kpull: float, ppull: float, alp: float, anopt: int):
    os.makedirs(workdir, exist_ok=True)
    _write_text(os.path.join(workdir, "start.xyz"), start_xyz_text)
    _write_text(os.path.join(workdir, "end.xyz"), end_xyz_text)
    path_inp = textwrap.dedent(f"""\
        $path
           nrun=1
           npoint={int(npoint)}
           anopt={int(anopt)}
           kpush={kpush:.6f}
           kpull={kpull:.6f}
           ppull={ppull:.6f}
           alp={alp:.6f}
        $end
    """)
    _write_text(os.path.join(workdir, "path.inp"), path_inp)
    cmd = ["xtb", "start.xyz", "--path", "end.xyz", "--input", "path.inp", "--gfn", str(int(gfn))]
    if alpb: cmd += ["--alpb", alpb]
    out = _run_xtb(cmd, cwd=workdir, nproc=nproc)
    runs = _parse_xtb_run_table(out)
    return runs, "\n".join(out.strip().splitlines()[-50:])

# ==========================================
# MAIN CALCULATION FUNCTION (FIXED)
# ==========================================
def estimate_barriers(rxn_smiles: str, workdir: str, gfn: int = 2, nproc: int = 2,
                      seed: int = 42, alpb: Optional[str] = None, 
                      num_confs_to_search=200, verbose: bool = False, **kwargs):

    # Settings mặc định khác
    npoint=200; kpush=0.008; kpull=-0.015; ppull=0.05; alp=0.4; anopt=10
    
    if verbose:
        print("="*60)
        print(f" Reaction: {rxn_smiles}")

    def run_optimization_cycle(force_indep, t_dist):
        try:
            s_xyz, e_xyz, s_mol, e_mol, break_map, form_map, opt_mode, strategy = build_start_end_xyz_smart(
                rxn_smiles, seed=seed, num_confs=num_confs_to_search,
                force_independent=force_indep, target_dist=t_dist
            )
            s_rc_bonds = get_rc_bonds_indices(s_mol, form_map, break_map)
            e_rc_bonds = get_rc_bonds_indices(e_mol, form_map, break_map)

            s_opt, E_start = xtb_optimize_double_step(s_xyz, workdir, "start", s_rc_bonds, gfn=gfn, nproc=nproc, alpb=alpb)
            e_opt, E_end = xtb_optimize_double_step(e_xyz, workdir, "end", e_rc_bonds, gfn=gfn, nproc=nproc, alpb=alpb)
            dE = 0.0
            if E_start and E_end: dE = E_end - E_start
            return dE, s_opt, e_opt, strategy
        except Exception as e:
            if verbose: print(f"   Error in cycle: {e}")
            return None, None, None, None

    def calc_barriers_internal(s_opt, e_opt, dE, strategy):
        try:
            s_opt_txt = _read_text(s_opt); e_opt_txt = _read_text(e_opt)
            if not check_atom_consistency(s_opt_txt, e_opt_txt): return None, None, None, None, None

            fw_runs, _ = run_xtb_path_once(s_opt_txt, e_opt_txt, os.path.join(workdir, "fw"),
                                           gfn, nproc, alpb, npoint, kpush, kpull, ppull, alp, anopt)
            fw_raw = min([r.barrier_kcal for r in fw_runs if r.barrier_kcal > 0.001], default=0.0) if fw_runs else None

            bw_runs, _ = run_xtb_path_once(e_opt_txt, s_opt_txt, os.path.join(workdir, "bw"),
                                           gfn, nproc, alpb, npoint, kpush, kpull, ppull, alp, anopt)
            bw_raw = min([r.barrier_kcal for r in bw_runs if r.barrier_kcal > 0.001], default=0.0) if bw_runs else None

            fw_adj = None; bw_adj = None
            if fw_raw is not None and bw_raw is not None:
                if strategy == "REACTANT_TEMPLATE": bw_adj = bw_raw; fw_adj = bw_raw + dE
                elif strategy == "PRODUCT_TEMPLATE": fw_adj = fw_raw; bw_adj = fw_raw - dE
                else: 
                    cand1_fwd = fw_raw; cand1_bwd = fw_raw - dE
                    cand2_bwd = bw_raw; cand2_fwd = bw_raw + dE
                    is_cand1_ok = (cand1_bwd >= -0.1); is_cand2_ok = (cand2_fwd >= -0.1)
                    if is_cand1_ok and not is_cand2_ok: fw_adj, bw_adj = cand1_fwd, cand1_bwd
                    elif is_cand2_ok and not is_cand1_ok: fw_adj, bw_adj = cand2_fwd, cand2_bwd
                    elif is_cand1_ok and is_cand2_ok:
                        if dE > 0: fw_adj, bw_adj = cand2_fwd, cand2_bwd
                        else: fw_adj, bw_adj = cand1_fwd, cand1_bwd
                    else:
                        if dE > 0: fw_adj, bw_adj = cand2_fwd, cand2_bwd
                        else: fw_adj, bw_adj = cand1_fwd, cand1_bwd
            return fw_raw, bw_raw, fw_adj, bw_adj, dE
        except Exception: return None, None, None, None, None

    # --- Phase 1: 2.0A ---
    dE, s_opt, e_opt, strategy = run_optimization_cycle(False, 2.0)
    fw_raw, bw_raw, fw_adj, bw_adj = None, None, None, None
    if dE is not None and abs(dE) < 200:
        fw_raw, bw_raw, fw_adj, bw_adj, _ = calc_barriers_internal(s_opt, e_opt, dE, strategy)

    need_retry_3A = False
    if dE is None or abs(dE) > 200: need_retry_3A = True
    elif fw_raw is None or bw_raw is None or fw_raw < 1.0 or bw_raw < 1.0: need_retry_3A = True

    # --- Phase 2: 3.0A ---
    if need_retry_3A:
        if verbose: print(f"   Retry 3.0A...")
        dE_2, s_opt_2, e_opt_2, strategy_2 = run_optimization_cycle(True, 3.0)
        if dE_2 is not None:
            dE, s_opt, e_opt, strategy = dE_2, s_opt_2, e_opt_2, strategy_2
            fw_raw, bw_raw, fw_adj, bw_adj, _ = calc_barriers_internal(s_opt, e_opt, dE, strategy)

    need_retry_5A = False
    if dE is None or abs(dE) > 200: need_retry_5A = True
    elif fw_raw is None or bw_raw is None or fw_raw < 1.0 or bw_raw < 1.0: need_retry_5A = True

    # --- Phase 3: 5.0A ---
    if need_retry_5A:
        if verbose: print(f"   Retry 5.0A...")
        dE_3, s_opt_3, e_opt_3, strategy_3 = run_optimization_cycle(True, 5.0)
        if dE_3 is not None:
            dE, s_opt, e_opt, strategy = dE_3, s_opt_3, e_opt_3, strategy_3
            fw_raw, bw_raw, fw_adj, bw_adj, _ = calc_barriers_internal(s_opt, e_opt, dE, strategy)

    if fw_raw is not None and bw_raw is not None:
        return fw_raw, bw_raw, fw_adj, bw_adj, dE
    else:
        return None, None, None, None, None